# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://repaircafeaarhus.github.io
title: Repair Cafe Aarhus
email: donotreply@22decembre.eu
author: Stephane
description: > # "Write an awesome description for your new site here. 
  Repair Cafe is a team of voluteers helping you to repair your bikes, clothes, computers and phones. Come at Dokk1 in Aarhus.
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Facebook
    url: https://www.facebook.com/RepairCafeAarhus/
